= Collections Workshops

Introductory level workshop. Everything is in one file, run it with `java Compartment.java`
The main aim is to explore `TreeMap<K,V>`

== General info

The task concerns the reservation of seats in the train compartment:

. start by implementing _Compartment_ class using _TreeMap_
. perform basic operations on that collection to solve the tasks

TIP: For details of the task see *Compartment.java*

== Technologies

* Java 15

[TIP]
.Hints
====
IMPORTANT: It is recommended that you read all the tasks before implementing, as this may determine your collection selection.

TIP: open Javadocs for the compartment class via `Ctrl+q` in Intellij, and dock the opened window. Renders as HTML and you won't have to scroll up and down while coding, as long as you don't click on something else where the docked view will change to that thing. If you dislike it, take a look at `jd.sh` script and try running that.

For further details see:

. [https://docs.oracle.com/en/java/javase/15/docs/api/java.base/java/util/Collection.html]
. [https://docs.oracle.com/en/java/javase/15/docs/api/java.base/java/util/Map.html]
====
